# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alienbot Portfolio
description: >- # this means to ignore newlines until "baseurl:"
  Cybersecurity Engineer | Blockchain security researcher
#twitter_username: username
github_username: FMessaoudi-01
#minimal_mistakes_skin: dark # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

# Added settings
date_format: "%Y-%m-%d"
enable_copy_code_button: true



# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
sass:
  style: compressed
  load_paths:
    - _sass   
    - assets/css
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Paris # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Fatma Messaoudi"
  avatar : "/assets/images/avatar.png"
  bio    : "Junior Cybersecurity Engineer on a forever learning journey."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://FMessaoudi-01.github.io"
    - label: "Linkedin"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/fmessaoudi/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/FMessaoudi-01"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://instagram.com/"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://FMessaoudi-01.github.io"
    - label: "Linkedin"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/fmessaoudi/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/FMessaoudi-01"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      toc: true
      author_profile: true
      show_date: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
